version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: dccprint
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

# APT
nfpms:
  - id: dccprint
    package_name: dccprint
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "fgonzalezurriola"
    homepage: "https://github.com/fgonzalezurriola/dccprint"
    maintainer: "Tu Nombre <tu@email.com>"
    description: "Herramienta de línea de comandos para impresión y procesamiento de documentos DCC"
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/dccprint/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/dccprint/LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: dccprint
    repository:
      owner: fgonzalezurriola
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/fgonzalezurriola/dccprint"
    description: "Herramienta de línea de comandos para impresión y procesamiento de documentos DCC"
    license: "GPL-3.0"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    install: |
      bin.install "dccprint"
    test: |
      system "#{bin}/dccprint --version"

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
