# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "dccprint"
    main: ./cmd/dccprint/
    binary: dccprint
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    # Removido el hook post problemático

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  replace_existing_draft: true
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nfpms:
  - id: dccprint
    package_name: dccprint
    vendor: "fgonzalezurriola"
    homepage: "https://github.com/fgonzalezurriola/dccprint"
    maintainer: "fgonzalezurriola <fgonzalezurriola@gmail.com>"
    description: "Una herramienta TUI para imprimir archivos en el DCC."
    license: "GPL-3.0-or-later"
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - glibc
    overrides:
      deb:
        dependencies:
          - libc6
      rpm:
        dependencies:
          - glibc
      apk:
        dependencies:
          - musl
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/dccprint/LICENSE
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/dccprint/README.md
        file_info:
          mode: 0644
    rpm:
      summary: "Herramienta TUI para imprimir archivos en el DCC"
      group: "Applications/System"
      packager: "fgonzalezurriola <fgonzalezurriola@gmail.com>"
    deb:
      fields:
        Bugs: "https://github.com/fgonzalezurriola/dccprint/issues"

brews:
  - name: dccprint
    homepage: "https://github.com/fgonzalezurriola/dccprint"
    description: "Una herramienta TUI para imprimir archivos en el DCC."
    install: |
      bin.install "dccprint"
    repository:
      owner: fgonzalezurriola
      name: homebrew-tap

aurs:
  - name: dccprint-bin
    homepage: "https://github.com/fgonzalezurriola/dccprint"
    description: "Una herramienta TUI para imprimir archivos en el DCC."
    maintainers:
      - "fgonzalezurriola <fgonzalezurriola@gmail.com>"
    license: "GPL-3.0-or-later"
    private_key: "{{ .Env.AUR_DCCPRINT_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/dccprint-bin.git"
    provides:
      - dccprint
    conflicts:
      - dccprint
    depends:
      - glibc
    package: |-
      install -Dm755 "./dccprint" "${pkgdir}/usr/bin/dccprint"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/dccprint-bin/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/dccprint-bin/README.md"
    commit_author:
      name: "fgonzalezurriola"
      email: "fgonzalezurriola@gmail.com"

snapcrafts:
  - id: dccprint
    ids:
      - dccprint
    name: dccprint
    title: "DCC Print"
    summary: "TUI para imprimir archivos en el DCC"
    description: |
      Una herramienta TUI que permite a los usuarios
      del DCC imprimir archivos de forma sencilla.
    grade: stable
    confinement: strict
    base: core22
    license: GPL-3.0-or-later
    publish: true
    channel_templates:
      - stable
    apps:
      dccprint:
        command: dccprint
        plugs:
          - home
          - network
